# ![Imgur](https://i.imgur.com/5pXzCIu.png)

# **DATA SCIENCE VA SUN'IY INTELLEKT PRAKTIKUM**

## Ma'lumotlar tahlili. Pandas kutubxonasi.

# **AMALIYOT**
## 3.1 Series va Index

### **1-mashq**. `Pandas` kutubxonasini `pd`, `numpy` kutubxonasini `np` deb chaqirib oling

In [48]:
import pandas as pd
import numpy as np

### **2-mashq.** O'zbekiston Respublikasi viloyatlaridan iborat bir o'lchamli Series obyektini yarating

In [49]:
obj = pd.Series(
    [
        "Andijon",
        "Buxoro",
        "Farg'ona",
        "Jizzax",
        "Xorazm",
        "Namangan",
        "Navoiy",
        "Qashqadaryo",
        "Qoraqalpog'iston Respublikasi",
        "Samarqand",
        "Sirdaryo",
        "Surxondaryo",
        "Toshkent",
    ]
)
print(obj)

0                           Andijon
1                            Buxoro
2                          Farg'ona
3                            Jizzax
4                            Xorazm
5                          Namangan
6                            Navoiy
7                       Qashqadaryo
8     Qoraqalpog'iston Respublikasi
9                         Samarqand
10                         Sirdaryo
11                      Surxondaryo
12                         Toshkent
dtype: object

### **3-mashq.** Yuqorida yaratilgan Series obyektining barcha qiymaltarini chiqaring

In [51]:
obj.values

array(['Andijon', 'Buxoro', "Farg'ona", 'Jizzax', 'Xorazm', 'Namangan',
       'Navoiy', 'Qashqadaryo', "Qoraqalpog'iston Respublikasi",
       'Samarqand', 'Sirdaryo', 'Surxondaryo', 'Toshkent'], dtype=object)

### **4-mashq.** Yuqoridagi Series obyektining eng birinchi qiymatini chiqaring

In [52]:
obj[0]

'Andijon'

### **5-mashq.** Yuqoridagi Series obyektining eng oxirgi qiymatini chiqaring

In [53]:
obj[12]

'Toshkent'

### **6-mashq.** Yuqoridagi Series obyekti uzunligini chiqaring

In [54]:
obj.size

13

### **7-mashq.** Yuqoridagi Series obyektining o'rtasidan 3 ta qiymat chiqaring

In [55]:
obj[[5, 6, 7]]

5       Namangan
6         Navoiy
7    Qashqadaryo
dtype: object

### **8-mashq.** Quyidagi Series obyektini yarating.
**Ahamiyat bering. `Series` obyekti indeksi sifatida viloyatlar nomi ishlatilgan**

In [56]:
int = obj.values
aholi = [
    1899000,
    1384700,
    2597000,
    910500,
    1200000,
    1862000,
    767500,
    2029000,
    1200000,
    2322000,
    648100,
    1676000,
    4450000,
]
obj2 = pd.Series(aholi, index=int)
print(obj2)

Andijon                          1899000
Buxoro                           1384700
Farg'ona                         2597000
Jizzax                            910500
Xorazm                           1200000
Namangan                         1862000
Navoiy                            767500
Qashqadaryo                      2029000
Qoraqalpog'iston Respublikasi    1200000
Samarqand                        2322000
Sirdaryo                          648100
Surxondaryo                      1676000
Toshkent                         4450000
dtype: int64

### **9-mashq.** Yuqoridagi `Series` obyektidan Jizzax, Buxoro va Namangan viloyatlarining aholisini chiqaring

In [57]:
obj2[["Jizzax", "Buxoro", "Namangan"]]

Jizzax       910500
Buxoro      1384700
Namangan    1862000
dtype: int64

### **10-mashq.** Yuqoridagi `Series` obyektidan aholi soni 1 milliondan kam va ko'p bo'lgan viloyatlarni alohida chiqaring

In [58]:
print("Aholisi 1 milliondan ko'p viloyatlar")
print(obj2[obj2 > 1_000_000])

Aholisi 1 milliondan ko'p viloyatlar
Andijon                          1899000
Buxoro                           1384700
Farg'ona                         2597000
Xorazm                           1200000
Namangan                         1862000
Qashqadaryo                      2029000
Qoraqalpog'iston Respublikasi    1200000
Samarqand                        2322000
Surxondaryo                      1676000
Toshkent                         4450000
dtype: int64

In [59]:

print("Aholisi 1 milliondan kam viloyatlar")
print(obj2[obj2 < 1_000_000])

Aholisi 1 milliondan kam viloyatlar
Jizzax      910500
Navoiy      767500
Sirdaryo    648100
dtype: int64

### **11-mashq.** Aholisi 1 milliondan ko'p davlatlar orasida Navoiy viloyati bor/yo'qligini tekshiring

In [60]:
"Navoiy" in obj2[obj2 > 1_000_000]

False

### **12-mashq.** Quyidagi lug'atda viloyatlar va ularning maydonlari berilgan. Lug'atdan yangi `Series` obyektini yarating va unga "Hududlar hajmi" deb nom bering

In [61]:
dict = {
    "Andijon": 4200,
    "Buxoro": 39400,
    "Farg'ona": 6800,
    "Jizzax": 20500,
    "Xorazm": 6300,
    "Namangan": 7900,
    "Navoiy": 110800,
    "Qashqadaryo": 28400,
    "Qoraqalpog'iston Respublikasi": 160000,
    "Samarqand": 16400,
    "Sirdaryo": 5100,
    "Surxondaryo": 20800,
    "Toshkent": 15300,
}

In [62]:
obj3 = pd.Series(dict)
obj3.name = "Hudular hajmi"
print(obj3)

Andijon                            4200
Buxoro                            39400
Farg'ona                           6800
Jizzax                            20500
Xorazm                             6300
Namangan                           7900
Navoiy                           110800
Qashqadaryo                       28400
Qoraqalpog'iston Respublikasi    160000
Samarqand                         16400
Sirdaryo                           5100
Surxondaryo                       20800
Toshkent                          15300
Name: Hudular hajmi, dtype: int64

### **13-mashq.** Yuqoridagi `Series` obyektidan hududi eng katta va eng kichik elementlarni chiqaring

In [63]:
print(f"Eng katta hudud: {obj3.idxmax()}")
print(f"Eng kichik hudud: {obj3.idxmin()}")

Eng katta hudud: Qoraqalpog'iston Respublikasi
Eng kichik hudud: Andijon

### **14-mashq.** Yuqoridagi eng katta va eng kichik hududlar aholisi sonini chiqaring

In [64]:
print(f"{obj3.idxmax()} aholisi {obj2[obj3.idxmax()]}")
print(f"{obj3.idxmin()} aholisi {obj2[obj3.idxmin()]}")

Qoraqalpog'iston Respublikasi aholisi 1200000
Andijon aholisi 1899000

### **15-mashq**. Yuqoridagi hudulardan O'zbekiston Respublikasi hududini hisoblang

In [65]:
sum(obj3)

441900

### **16-mashq.** Aholisi eng ko'p va eng kam hududlarning hajmini va aholi sonini chiqaring

In [66]:
print(f"{obj2.idxmax()} hududi {obj3[obj2.idxmax()]}kv.km, aholisi {obj2[obj2.idxmax()]}")
print(f"{obj2.idxmin()} hududi {obj3[obj2.idxmin()]}kv.km, aholisi {obj2[obj2.idxmin()]}")

Toshkent hududi 15300kv.km, aholisi 4450000
Sirdaryo hududi 5100kv.km, aholisi 648100

### **17-mashq.** Yuqoridagi ikki obyektdan foydalangan holda O'zbekiston respublikasi tarkibidagi hududlarni avval aholi soni bo'yicha, keyin esa hajmi bo'yicha tartiblab chiqaring

In [67]:
print("Hududlar hajmi bo'yicha tartiblash")
obj3.sort_values()

Hududlar hajmi bo'yicha tartiblash

Andijon                            4200
Sirdaryo                           5100
Xorazm                             6300
Farg'ona                           6800
Namangan                           7900
Toshkent                          15300
Samarqand                         16400
Jizzax                            20500
Surxondaryo                       20800
Qashqadaryo                       28400
Buxoro                            39400
Navoiy                           110800
Qoraqalpog'iston Respublikasi    160000
Name: Hudular hajmi, dtype: int64

In [68]:
print("Aholi soni bo'yicha tartiblash")
obj2.sort_values()

Aholi soni bo'yicha tartiblash

Sirdaryo                          648100
Navoiy                            767500
Jizzax                            910500
Xorazm                           1200000
Qoraqalpog'iston Respublikasi    1200000
Buxoro                           1384700
Surxondaryo                      1676000
Namangan                         1862000
Andijon                          1899000
Qashqadaryo                      2029000
Samarqand                        2322000
Farg'ona                         2597000
Toshkent                         4450000
dtype: int64